import React, { useEffect, useRef, useState } from 'react';
import {
  ArrowDown,
  ArrowUpRight,
  Code2,
  Mail,
  MapPin,
  Menu,
  Moon,
  Sun,
  X,
} from 'lucide-react';

const navItems = [
  ['about', 'About'],
  ['experience', 'Experience'],
  ['skills', 'Skills'],
  ['projects', 'Projects'],
  ['contact', 'Contact'],
];

const experience = [
  {
    company: 'Microsoft',
    role: 'Senior Software Engineer',
    period: 'Dec 2022 — Present',
    team: 'OneDrive & SharePoint · Mountain View, California',
    logo: '/assets/img/microsoft-logo.png',
    points: [
      'Implemented a natural-language-to-SQL query converter with the Claude Sonnet AI model.',
      'Simplified database health incident troubleshooting with a Claude harness.',
      'Reduced on-call engineer workload by 30% by leveraging Microsoft Semantic Kernel.',
      'Reduced compute utilization through asynchronous invocation for Azure SQL pool and database operations.',
      'Introduced a distributed database monitoring platform for 180,000 databases.',
      'Updated service databases with passwordless authentication using Microsoft Entra ID.',
      'Introduced Unified Auto Heal, reducing incident mitigation time by 38%.',
      'Increased fault tolerance through partial pool failover to geo-recovery.',
    ],
  },
  {
    company: 'Microsoft',
    role: 'Software Engineer II',
    period: 'Apr 2020 — Dec 2022',
    team: 'OneDrive & SharePoint · Redmond, Washington',
    logo: '/assets/img/microsoft-logo.png',
    points: [
      'Improved database infrastructure management for SharePoint.',
      'Implemented reliability, latency, error count, and API gateway monitoring.',
      'Identified and mitigated scalability issues in Azure resource monitoring jobs.',
      'Contributed to a domain-less reliable computational infrastructure.',
      'Introduced a firewall handler to secure SQL servers.',
    ],
  },
  {
    company: 'Cisco',
    role: 'Software Engineer III',
    period: 'Jun 2018 — Apr 2020',
    team: 'Digital Network Architecture · San Jose, California',
    logo: '/assets/img/Cisco-logo.png',
    points: [
      'Reduced compute utilization for a real-time platform that analyzes, manages, and troubleshoots networking devices.',
      'Delivered full-stack features with Java, JAX-RS, Apache Beam, Gremlin TinkerPop, and Elasticsearch.',
      'Developed REST APIs to extract device metrics from the device platform.',
      'Identified usage statistics, enhanced streaming workflows, and introduced monitoring-based troubleshooting.',
      'Implemented interfaces to fetch real-time issues generated by network devices.',
      'Worked across Apache Flink, Apache Beam, Kubernetes, Elasticsearch, and Java.',
    ],
  },
  {
    company: 'Orion Health',
    role: 'Software Engineer II',
    period: 'Dec 2017 — Jun 2018',
    team: 'Business Intelligence & Analytics · Scottsdale, Arizona',
    logo: '/assets/img/Orion-Health-Logo.png',
    points: [
      'Enhanced a medical analytics platform built with Apache Spark Streaming, Scala, Kafka, and Elasticsearch.',
      'Implemented ETL jobs that aggregate meaningful attributes from healthcare data.',
      'Built a stable platform that handles high-volume real-time data and provides end-user metrics.',
      'Developed Apache Spark workloads using DataFrames, Datasets, RDDs, and DStreams.',
      'Worked with Git, Jira, Jenkins pipelines, and Amazon Web Services.',
    ],
  },
  {
    company: 'Orion Health',
    role: 'Software Engineer I',
    period: 'Jan 2017 — Dec 2017',
    team: 'Business Intelligence & Analytics · Scottsdale, Arizona',
    logo: '/assets/img/Orion-Health-Logo.png',
    points: [
      'Contributed to a medical analytics platform using Apache Spark, Scala, Java, and Elasticsearch.',
      'Developed REST APIs using Java, J2EE, JAX-RS, and REST services.',
      'Developed React interfaces using ES6, Webpack, Redux, and JavaScript.',
      'Collaborated closely on features and peer-reviewed other developers’ code.',
    ],
  },
  {
    company: 'Alcatel',
    role: 'Application & Development Intern',
    period: 'May 2016 — Aug 2016',
    team: 'Microservices & Cloud Platform · San Diego, California',
    logo: '/assets/img/alcatel.jpg',
    points: [
      'Developed RESTful services in Go for an IoT application.',
      'Managed a distributed cluster and supported a production release through a Docker image.',
      'Deployed applications with Apache Mesosphere, Apache Marathon, and Docker Machine.',
      'Worked with Linux virtualization through QEMU, KVM, and libvirt.',
      'Used Amazon Web Services and Elastic Compute Cloud.',
    ],
  },
  {
    company: 'QuEST Global',
    role: 'Software Engineer',
    period: 'Oct 2013 — Nov 2014',
    team: 'Toshiba Medical Systems / PIMS · Trivandrum, Kerala',
    logo: '/assets/img/quest_logo.jpg',
    points: [
      'Contributed to PIMS development through all phases of the software lifecycle, from requirements through deployment.',
      'Provided requirements analysis, design, and programming support for PIMS enhancements.',
      'Assisted senior developers in creating quick fixes for software workflow defects.',
      'Developed troubleshooting skills through log analysis and hands-on implementation of design patterns.',
    ],
  },
];

const skillGroups = {
  Languages: ['Java', 'C#', 'Go', 'Python', 'JavaScript'],
  Systems: ['AI Infrastructure', 'Harness Engineering', 'Agentic Systems', 'Distributed Computing', 'Platform Engineering', 'Reliability Engineering', 'Microservices', 'Observability', 'System Design'],
  Cloud: ['Microsoft Azure', 'Cloud Architecture', 'Kubernetes', 'Docker', 'Apache Mesos', 'Apache Marathon'],
  'Data & AI': ['Apache Spark', 'Apache Flink', 'Apache Beam', 'Microsoft Semantic Kernel', 'LangChain', 'PyTorch'],
};

const projects = [
  {
    title: 'Scaling Computational Geometry',
    image: '/assets/img/port01.jpg',
    description: 'Distributed geospatial operations across a Spark cluster, backed by Hadoop HDFS and the JTS topology suite.',
    tags: ['Java', 'Spark', 'Hadoop'],
    source: 'https://github.com/karthiklsarma/GeospatialOperations',
  },
  {
    title: 'Wiki Generator',
    image: '/assets/img/port02.png',
    description: 'A collaborative chat application that identifies high-quality tagged conversations and turns them into a structured wiki.',
    tags: ['Node.js', 'MongoDB', 'Analytics'],
    source: 'https://github.com/adi06/WikiGenerator',
  },
  {
    title: 'Discourse-Centric Data',
    image: '/assets/img/port03.jpg',
    description: 'Topic Facet Modeling and D3 visualizations that surface conceptual topics and valuable posts from learning forums.',
    tags: ['D3.js', 'Data modeling', 'Research'],
    source: 'https://github.com/karthiklsarma/Modelling-Discourse-Centric-Data',
    demo: '/Project/index.html',
  },
  {
    title: 'Optical Data Mining',
    image: '/assets/img/port04.jpg',
    description: 'Disease susceptibility classification from optical image attributes, reaching 84% accuracy with ensemble models.',
    tags: ['Python', 'Random Forest', 'AdaBoost'],
    source: 'https://github.com/karthiklsarma/Optical-Data-Mining',
  },
  {
    title: 'Secure Banking System',
    image: '/assets/img/port05.JPG',
    description: 'Concurrent internet banking with PKI-backed transaction security, OTP verification, and account management.',
    tags: ['Java', 'Spring', 'MySQL'],
    source: 'https://github.com/karthiklsarma/SecureBankingSystem',
  },
  {
    title: 'Go Web Services',
    image: '/assets/img/port06.jpg',
    description: 'A collection of REST services, concurrency patterns, serializers, data structures, and I/O programs written in Go.',
    tags: ['Go', 'REST', 'Concurrency'],
    source: 'https://github.com/karthiklsarma/Go-Programs',
  },
  {
    title: 'US Open Analytics',
    image: '/assets/img/port07.jpg',
    description: 'Ten years of championship data explored through linked graphs, player error statistics, histograms, and pie charts.',
    tags: ['JavaScript', 'D3.js', 'Visualization'],
    demo: '/Analytics/index.html',
  },
  {
    title: 'Cross Validated Explorer',
    image: '/assets/img/port08.jpg',
    description: 'A visual analytics dashboard for discovering topic relationships and valuable contributions across 14,000 forum posts.',
    tags: ['R', 'D3.js', 'Cosine similarity'],
    source: 'https://github.com/karthiklsarma/CrossValidated-Analysis',
    demo: '/DataViz/index.html',
  },
];

const courses = [
  'Foundations of Algorithms', 'Distributed Database Systems', 'Distributed Software Development',
  'Software Security', 'Semantic Web Mining', 'Software Analysis and Design', 'Data Mining',
  'Online Learning Communities', 'Applied Cryptography', 'Data Visualization',
];

const activities = [
  'Desk Assistant — Residential Housing',
  'Transcriber — W. P. Carey School of Business',
  'Customer Service Associate — Sun Devil Campus Stores',
  'Lifeguard — Sun Devil Fitness Center',
];

function useActiveSection() {
  const [active, setActive] = useState('about');

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)),
      { rootMargin: '-35% 0px -55%', threshold: 0 },
    );
    navItems.forEach(([id]) => {
      const element = document.getElementById(id);
      if (element) observer.observe(element);
    });
    return () => observer.disconnect();
  }, []);

  return active;
}

function useReveal() {
  const ref = useRef(null);

  useEffect(() => {
    const element = ref.current;
    if (!element) return undefined;
    const observer = new IntersectionObserver(
      ([entry]) => entry.isIntersecting && element.classList.add('is-visible'),
      { threshold: 0.12 },
    );
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  return ref;
}

function Reveal({ children, className = '' }) {
  const ref = useReveal();
  return <div ref={ref} className={`reveal ${className}`}>{children}</div>;
}

function SectionHeading({ eyebrow, title, copy }) {
  return (
    <div className="section-heading">
      <p className="eyebrow">{eyebrow}</p>
      <h2>{title}</h2>
      {copy && <p className="section-copy">{copy}</p>}
    </div>
  );
}

function Header() {
  const active = useActiveSection();
  const [open, setOpen] = useState(false);
  const [dark, setDark] = useState(() => localStorage.getItem('theme') === 'dark');

  useEffect(() => {
    document.documentElement.dataset.theme = dark ? 'dark' : 'light';
    localStorage.setItem('theme', dark ? 'dark' : 'light');
  }, [dark]);

  return (
    <header className="site-header">
      <a className="monogram" href="#about" aria-label="Karthik Sarma, home">KS<span>.</span></a>
      <nav className={open ? 'nav-links is-open' : 'nav-links'} aria-label="Main navigation">
        {navItems.map(([id, label]) => (
          <a key={id} className={active === id ? 'active' : ''} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>
        ))}
        <a className="resume-link" href="/assets/resume/Karthik-Resume-web.pdf">Résumé <ArrowUpRight size={14} /></a>
      </nav>
      <div className="header-actions">
        <button className="icon-button" onClick={() => setDark((value) => !value)} aria-label="Toggle color theme">
          {dark ? <Sun size={19} /> : <Moon size={19} />}
        </button>
        <button className="icon-button menu-button" onClick={() => setOpen((value) => !value)} aria-label="Toggle menu">
          {open ? <X size={20} /> : <Menu size={20} />}
        </button>
      </div>
    </header>
  );
}

function Hero() {
  return (
    <section className="hero" id="about">
      <div className="hero-image" aria-hidden="true" />
      <div className="hero-shade" aria-hidden="true" />
      <div className="hero-content">
        <div className="hero-status"><span /> AI platform engineering at Microsoft</div>
        <p className="hero-kicker">Senior Software Engineer · Mountain View, CA</p>
        <h1>Karthik<br />Sarma<span>.</span></h1>
        <p className="hero-intro">I build AI-powered developer tools, distributed systems, and cloud infrastructure at serious scale.</p>
        <div className="hero-actions">
          <a className="button primary" href="#projects">Explore my work <ArrowDown size={17} /></a>
          <a className="button ghost" href="mailto:karthikl_sarma@yahoo.com">Start a conversation <ArrowUpRight size={17} /></a>
        </div>
      </div>
      <div className="hero-index" aria-hidden="true">01 / 05</div>
    </section>
  );
}

function About() {
  return (
    <section className="about-section page-section">
      <Reveal className="about-grid">
        <div>
          <p className="eyebrow">Profile / 2026</p>
          <h2 className="statement">Platform engineer.<br /><em>AI systems builder.</em></h2>
        </div>
        <div className="about-copy">
          <p>I’m a senior software engineer with 12+ years of experience building large-scale distributed systems, cloud infrastructure, database platforms, and AI-powered developer productivity solutions.</p>
          <p>My work spans Microsoft Azure, distributed monitoring, reliability engineering, Semantic Kernel, harness engineering, Claude Code, GitHub Copilot, and AI-assisted software development.</p>
          <a className="text-link" href="/Interactive-Resume/index.html">Open interactive résumé <ArrowUpRight size={16} /></a>
        </div>
      </Reveal>
      <Reveal className="metric-strip">
        <div><strong>12+</strong><span>Years building software</span></div>
        <div><strong>4</strong><span>Industries explored</span></div>
        <div><strong>3</strong><span>Cloud platforms</span></div>
        <div><strong>∞</strong><span>Curiosity remaining</span></div>
      </Reveal>
    </section>
  );
}

function Education() {
  return (
    <section className="education-section page-section">
      <Reveal>
        <SectionHeading eyebrow="Education" title="Built on strong foundations." />
        <div className="education-grid">
          <article className="education-item">
            <img src="/assets/img/asu_seal.jpg" alt="Arizona State University seal" />
            <div><span>Jan 2015 — Dec 2016</span><h3>Master of Computer Science</h3><p>Arizona State University · Tempe, Arizona · GPA 3.5</p></div>
          </article>
          <article className="education-item">
            <img src="/assets/img/uok_seal.jpg" alt="University of Kerala seal" />
            <div><span>Jun 2009 — Jul 2013</span><h3>Bachelor of Technology</h3><p>University of Kerala · Trivandrum, India · GPA 3.8</p></div>
          </article>
        </div>
        <div className="course-list">
          <p className="eyebrow">Selected coursework</p>
          {courses.map((course, index) => <span key={course}>{String(index + 1).padStart(2, '0')} · {course}</span>)}
        </div>
      </Reveal>
    </section>
  );
}

function Experience() {
  const [showAll, setShowAll] = useState(false);
  const visible = showAll ? experience : experience.slice(0, 3);

  return (
    <section className="experience-section page-section" id="experience">
      <Reveal>
        <SectionHeading eyebrow="Experience" title="A decade of shipping at scale." copy="From healthcare analytics to AI-powered developer tooling and global database infrastructure, the through-line is dependable engineering for consequential systems." />
        <div className="timeline">
          {visible.map((job, index) => (
            <article className="job" key={`${job.company}-${job.role}`}>
              <div className="job-number">{String(index + 1).padStart(2, '0')}</div>
              <div className="job-logo"><img src={job.logo} alt="" /></div>
              <div className="job-main">
                <p className="job-period">{job.period}</p>
                <h3>{job.role}</h3>
                <p className="job-company">{job.company} · {job.team}</p>
              </div>
              <ul>{job.points.map((point) => <li key={point}>{point}</li>)}</ul>
            </article>
          ))}
        </div>
        <button className="button outline show-more" onClick={() => setShowAll((value) => !value)}>
          {showAll ? 'Show recent roles' : 'View full career'} <ArrowDown className={showAll ? 'rotate' : ''} size={17} />
        </button>
      </Reveal>
    </section>
  );
}

function Skills() {
  const [activeGroup, setActiveGroup] = useState('Languages');

  return (
    <section className="skills-section page-section" id="skills">
      <Reveal className="skills-layout">
        <SectionHeading eyebrow="Capabilities" title="Deep systems knowledge. Broad technical range." />
        <div className="skills-panel">
          <div className="skill-tabs" role="tablist" aria-label="Skill categories">
            {Object.keys(skillGroups).map((group) => (
              <button key={group} className={activeGroup === group ? 'active' : ''} onClick={() => setActiveGroup(group)} role="tab" aria-selected={activeGroup === group}>{group}</button>
            ))}
          </div>
          <div className="skill-cloud" role="tabpanel">
            {skillGroups[activeGroup].map((skill, index) => <span key={skill}><sup>{String(index + 1).padStart(2, '0')}</sup>{skill}</span>)}
          </div>
        </div>
        <div className="activity-block">
          <p className="eyebrow">Beyond the screen</p>
          {activities.map((activity) => <span key={activity}>{activity}</span>)}
        </div>
      </Reveal>
    </section>
  );
}

function Projects() {
  return (
    <section className="projects-section page-section" id="projects">
      <Reveal>
        <SectionHeading eyebrow="Selected projects" title="Experiments with purpose." copy="A working archive spanning distributed computing, security, analytics, and data visualization." />
        <div className="projects-grid">
          {projects.map((project, index) => (
            <article className="project-card" key={project.title}>
              <div className="project-image">
                <img src={project.image} alt="" />
                <span>{String(index + 1).padStart(2, '0')}</span>
              </div>
              <div className="project-content">
                <div className="project-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>
                <h3>{project.title}</h3>
                <p>{project.description}</p>
                <div className="project-links">
                  {project.source && <a href={project.source} target="_blank" rel="noreferrer"><Code2 size={16} /> Source</a>}
                  {project.demo && <a href={project.demo}>Live project <ArrowUpRight size={16} /></a>}
                </div>
              </div>
            </article>
          ))}
        </div>
      </Reveal>
    </section>
  );
}

function Contact() {
  return (
    <footer className="contact-section" id="contact">
      <Reveal>
        <p className="eyebrow">Contact / Let’s build</p>
        <h2>Have a hard problem?<br /><em>Bring it over.</em></h2>
        <a className="contact-email" href="mailto:karthikl_sarma@yahoo.com">karthikl_sarma@yahoo.com <ArrowUpRight /></a>
        <div className="footer-row">
          <div><MapPin size={17} /> Seattle, Washington</div>
          <div className="socials">
            <a href="https://github.com/karthiklsarma" aria-label="GitHub"><Code2 /></a>
            <a href="https://www.linkedin.com/in/karthik-sarma-6713b416" aria-label="LinkedIn"><ArrowUpRight /></a>
            <a href="mailto:karthikl_sarma@yahoo.com" aria-label="Email"><Mail /></a>
          </div>
          <p>© {new Date().getFullYear()} Karthik Sarma</p>
        </div>
      </Reveal>
    </footer>
  );
}

export default function App() {
  return (
    <>
      <Header />
      <main>
        <Hero />
        <About />
        <Education />
        <Experience />
        <Skills />
        <Projects />
      </main>
      <Contact />
    </>
  );
}
